### ISSUE TITLE
1 to many ID correspondance when translating 

### ISSUE THREAD

**Issue by JoseCorCab** [seoanezonjic/ExpHunterSuite#20]
There is a loss of information beacause 1 gene ID from one nomenclature may correspond to many IDs in another nomenclature. It's very important to control this situation

**Comment by jimrperkins** [comment]
I will assume that the poster is referring to the situation where one input ID (e.g. ENSEMBL ID) might correspond to two or more ENTREZ IDs. This would be a problem for functional analysis, because a single DEG from the experiment could get translated to two ENTREZ genes that are likely to belong to the same functional group. This will lead to the gene being counted twice and lead to inflated significance in e.g. ORA analysis.

However, the poster need not worry - the way that the ENTREZ genes are mapped to the input genes means that there is AT MOST one ENTREZ gene per input gene. THerefore we will not "double count" the gene in the funcitonal enrichment analysis
